// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package org.demo.protobuf;

public final class StudentOuterClass {
  private StudentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_demo_protobuf_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_demo_protobuf_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_demo_protobuf_Student_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_demo_protobuf_Student_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_demo_protobuf_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_demo_protobuf_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_demo_protobuf_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_demo_protobuf_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\021org.demo.protobuf\"\374\001\n\007S" +
      "tudent\022\n\n\002id\030\001 \001(\005\022\022\n\nfirst_name\030\002 \001(\t\022\021" +
      "\n\tlast_name\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\0225\n\005phon" +
      "e\030\005 \003(\0132&.org.demo.protobuf.Student.Phon" +
      "eNumber\032Q\n\013PhoneNumber\022\016\n\006number\030\001 \001(\t\0222" +
      "\n\004type\030\002 \001(\0162$.org.demo.protobuf.Student" +
      ".PhoneType\"%\n\tPhoneType\022\n\n\006MOBILE\020\000\022\014\n\010L" +
      "ANDLINE\020\001\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\"" +
      "\035\n\nHelloReply\022\017\n\007message\030\001 \001(\tB\025\n\021org.de" +
      "mo.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_demo_protobuf_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_demo_protobuf_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_demo_protobuf_Student_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "Phone", });
    internal_static_org_demo_protobuf_Student_PhoneNumber_descriptor =
      internal_static_org_demo_protobuf_Student_descriptor.getNestedTypes().get(0);
    internal_static_org_demo_protobuf_Student_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_demo_protobuf_Student_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_org_demo_protobuf_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_demo_protobuf_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_demo_protobuf_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_demo_protobuf_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_demo_protobuf_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_demo_protobuf_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
